version: '3.8'

services:
  vote:
    container_name: vote
    build: ./vote
    ports:
      - 8080:80
    depends_on:
      - redis


  result:
    container_name: result
    build: ./result
    ports:
      - 8081:80
    depends_on:
      - db

  worker:
    container_name: worker
    build: ./worker
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis-data:/data

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "prueba@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "prueba1234"
    ports:
      - 5002:80

volumes:
  db-data:
  redis-data:
